name: shelter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  image_picker: ^0.8.5+3
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_bloc: ^8.1.6
  geolocator: ^13.0.1
  fluttertoast: ^8.2.8 
  supabase_flutter: ^2.8.0
  cloudinary_url_gen: ^1.6.0
  cloudinary_flutter: ^1.3.0
  flutter_dotenv:
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  location: ^7.0.1
  flutter_launcher_icons: ^0.14.1
  camera: ^0.11.0+2
  path: ^1.9.0
  path_provider: ^2.1.5
  get: ^4.6.6
  shared_preferences: ^2.3.2
  flutter_localization: ^0.2.2
  bloc: ^8.1.4
  country_pickers: ^3.0.1
  pin_code_fields: ^8.0.1
  flutter_screenutil:
  transparent_image:
  flutter_svg:
  lottie: ^3.1.3
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  share_plus:
  google_maps_flutter: ^2.9.0
  geocode: ^1.0.3
  dio: ^5.7.0
  geocoding:
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/res/logo.png"
  adaptive_icon_background: "#FFFAF1FD"
  adaptive_icon_foreground: "lib/res/logo.png"
flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/res/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


  